WIP: Update OpenEMS theme
OpenEMS/openems.io-theme pull request #1
Opened 2024-08-01 13:27 UTC by saeedniko

2024-08-08 08:43 UTC, da-Kai commented
@saeedniko ich habe eine release action hinzugefügt
Nach einem Merge zum master-branch wird in draf release erstellt.

mit "https://github.com/OpenEMS/openems.io-theme/releases/latest/download/ui-bundle.zip" bekommt man dann immer das ui-bundle des letzten releases.

2024-08-14 07:17 UTC, da-Kai requested changes

2024-08-14 07:17 UTC, da-Kai commented on src/img/feneco.ico
Brauchen wir diese Datei?

2024-08-14 07:47 UTC, saeedniko commented on src/img/feneco.ico
Nein, habe ich schon gelöscht

2024-08-14 12:24 UTC, da-Kai approved these changes

2024-08-15 19:25 UTC, merged